datasets:
  background:
    method: reflected
    parameters:
      min_distance_input: 1 deg
  containment_correction: false
  geom:
    axes:
      energy:
        max: 50 TeV
        min: 5 GeV
        nbins: 20
      energy_true:
        max: 50 TeV
        min: 5 GeV
        nbins: 20
    selection:
      offset_max: 2.5 deg
    wcs:
      binsize: 0.02 deg
      binsize_irf: 0.2 deg
      skydir:
        frame: icrs
        lat: 39.76017034 deg
        lon: 253.46756699 deg
      width:
        height: 2.0 deg
        width: 2.0 deg
  on_region:
    frame: icrs
    lat: 39.76017034 deg
    lon: 253.46756699 deg
    radius: 0.2 deg
  stack: true
  type: 1d
fit:
  fit_range:
    max: 50 TeV
    min: 50 GeV
flux_points:
  energy:
    max: 50 TeV
    min: 50 GeV
    nbins: 15
  source: Mrk501
general:
  log:
    level: info
light_curve:
  energy_edges:
    max: 50 TeV
    min: 100 GeV
    nbins: 1
  source: Mrk501
observations:
  datastore: build/Mrk501/dl3
  obs_time:
    start: '2020-05-01'
    stop: '2022-07-01'
  required_irf:
  - aeff
  - edisp
