components:
- name: M87
  spectral:
    parameters:
    - min: 0
      name: amplitude
      unit: cm-2 s-1 TeV-1
      value: 6.0e-11
    - name: index
      unit: ''
      value: 2.2
    - frozen: true
      name: reference
      unit: GeV
      value: 100
    type: PowerLawSpectralModel
  type: SkyModel
