components:
- name: 1ES1959+650
  spectral:
    model1:
      parameters:
      - min: 0
        name: amplitude
        unit: cm-2 s-1 TeV-1
        value: 6.0e-11
      - name: index
        unit: ''
        value: 2.2
      - name: lambda_
        unit: TeV-1
        value: 0.1
      - frozen: true
        name: reference
        unit: GeV
        value: 100
      type: ExpCutoffPowerLawSpectralModel
    model2:
      filename: ebl_dominguez11.fits.gz
      parameters:
      - name: alpha_norm
        value: 1.0
      - name: redshift
        value: 0.048
      type: EBLAbsorptionNormSpectralModel
    operator: mul
    type: CompoundSpectralModel
  type: SkyModel
